[package]
name = "stackit"
version = "0.1.0"
authors = ["_Bare <bare@logixsr.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5.1"
slab = "0.4.2"
rand = "0.7.3"
